import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navigation } from "./(utils)/(nav)/navigation";
import { AuthProvider } from "./AuthContext";
import { CartProvider } from "./CartContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased
         min-h-screen relative`}
      >
        <div className="absolute inset-0 bg-gradient-to-tr from-green-500/60 via-teal-400/60 to-blue-100/60"></div>
        <div className="absolute inset-0 bg-black/90 backdrop-blur-xl"></div>
        <div className="relative z-10 text-white">
          <AuthProvider>
            <CartProvider>
              <Navigation/>
              {children}
            </CartProvider>
          </AuthProvider>
        </div>
      </body>
    </html>
  );
}
